CREATE TABLE barbeiros(

   id BIGINT UNIQUE AUTO_INCREMENT,
   nome VARCHAR(255) NOT NULL,
   email VARCHAR(100) NOT NULL UNIQUE,
   cpf VARCHAR(20) NOT NULL UNIQUE,
   telefone VARCHAR(11) NOT NULL,
   especialidade VARCHAR(100) NOT NULL,

   PRIMARY KEY(id)

);